project:
  name: quickstart-newrelic-ct
  owner: quickstart@amazon.com
  package_lambda: false
  s3_bucket: 'tcat-quickstart-newrelic-ct-92lc75zt'
tests:
  newrelic-onboarding-us-west-2:
    parameters:
      NewRelicAccountNumber: ''
      LaunchAccountList: ''
      NewRelicAccessKey: ''
      StackSetName: 'NewRelic-Integration'
      StackSetUrl: 'https://wellsiau-quickstart.s3.amazonaws.com/newrelic/templates/newrelic-stack-set.yml'
      QSS3BucketName: 'wellsiau-quickstart'
      QSS3KeyPrefix: 'newrelic/'
    regions:
      - us-west-2
    template: templates/control-tower-customization.yml
